"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var calculadora_1 = require("./calculadora");
var calculadora = new calculadora_1.Calculadora();
var resSoma = calculadora.somar(250, 150);
var resSbtracao = calculadora.subtrair(250, 150);
var resMultiplicacao = calculadora.multiplicar(6, 6);
var resDivisao = calculadora.dividir(600, 3);
var resPotencia = calculadora.potencia(2, 5);
console.log(calculadora.exibirMensagem('soma', resSoma));
console.log(calculadora.exibirMensagem('subtrair', resSbtracao));
console.log(calculadora.exibirMensagem('multiplicar', resMultiplicacao));
console.log(calculadora.exibirMensagem('dividir', resDivisao));
console.log(calculadora.exibirMensagem('potencia', resPotencia));
